#!/usr/bin/env python3
"""Check every block/item model's box unwrap against the vanilla rule.

A 1.20.1 model element carries the same six faces a 1.7.10 Techne box did, but the
hand-written JSONs in this project were generated by a script that got two of them
wrong: `up` was given the rect that belongs to `down`, and `east` and `west` were
swapped. That is invisible to every server-side test and to the data validator - it
only shows up as a mirrored or upside-down texture on a face in game.

The authoritative rects, read out of `ModelPart$Cube`'s constructor, are, with the
box `addBox(x, y, z, w, h, d)` at `texOffs(u, v)` on a `texW` x `texH` sheet and all
lengths scaled into the model format's 0..16 uv space:

    U = u*16/texW   V = v*16/texH
    Wu = w*16/texW  Hu = h*16/texH
    Dx = d*16/texW  Dy = d*16/texH

    down  = (U+Dx,       V, U+Dx+Wu,      V+Dy)
    up    = (U+Dx+Wu,    V, U+Dx+2*Wu,    V+Dy)
    west  = (U,          V+Dy, U+Dx,       V+Dy+Hu)
    north = (U+Dx,       V+Dy, U+Dx+Wu,    V+Dy+Hu)
    east  = (U+Dx+Wu,    V+Dy, U+Dx+Wu+Dx, V+Dy+Hu)
    south = (U+2*Dx+Wu,  V+Dy, U+2*Dx+2*Wu, V+Dy+Hu)

`u` and `v` are not known from the file, so they are recovered as the smallest
coordinate any face uses - which holds whether or not east/west and up/down were
swapped, because the swap only permutes rects that all sit in the same band.

The sheet size is not in the file either, so every plausible size is tried and the
one that makes all six faces agree is taken.

Not every model in the project was generated from a Techne box. The hand-written
ones - `essentia_dynamo`, `flower_dynamo`, `mana_fabricator`, and the `*_inv` and
`fountain` placeholders - give each face its own sprite region on purpose, and the
Techne band layout simply does not describe them. Judging those against it reports a
wall of false positives and buries the real ones, so a file is only judged at all
when at least half of its judgeable elements already follow the rule; the rest are
listed as "not judged" instead of counted as findings.

    python tools/check_unwrap.py            # report
    python tools/check_unwrap.py --json     # machine-readable
    python tools/check_unwrap.py --fix      # repair pure swaps in judged files

Exit code is the number of offending elements.
"""

from __future__ import annotations

import argparse
import json
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "src/main/resources/assets/technom"
MODEL_DIRS = (ASSETS / "models/block", ASSETS / "models/item")
TEXTURES = ASSETS / "textures"

EPS = 1.0e-3
FACES = ("down", "up", "north", "south", "west", "east")
# Sheet sizes the original mod actually used; the model's own texture reference is
# tried first, then these.
CANDIDATE_SIZES = ((16, 16), (32, 32), (64, 32), (64, 64), (128, 64), (256, 128))


def png_size(path: Path) -> tuple[int, int] | None:
    try:
        head = path.read_bytes()[:24]
    except OSError:
        return None
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    return struct.unpack(">II", head[16:24])


def referenced_sizes(model: dict) -> list[tuple[int, int]]:
    sizes = []
    for value in (model.get("textures") or {}).values():
        if not isinstance(value, str) or value.startswith("#") or ":" not in value:
            continue
        namespace, path = value.split(":", 1)
        if namespace != "technom":
            continue
        size = png_size(TEXTURES / f"{path}.png")
        if size and size not in sizes:
            sizes.append(size)
    return sizes


def rect_eq(got: list[float], want: tuple[float, ...]) -> bool:
    return all(abs(g - w) <= EPS for g, w in zip(got, want))


def predict(u: float, v: float, w: float, h: float, d: float,
            tex_w: int, tex_h: int) -> dict[str, tuple[float, ...]]:
    wu, hu = w * 16.0 / tex_w, h * 16.0 / tex_h
    dx, dy = d * 16.0 / tex_w, d * 16.0 / tex_h
    return {
        "down": (u + dx, v, u + dx + wu, v + dy),
        "up": (u + dx + wu, v, u + dx + 2 * wu, v + dy),
        "west": (u, v + dy, u + dx, v + dy + hu),
        "north": (u + dx, v + dy, u + dx + wu, v + dy + hu),
        "east": (u + dx + wu, v + dy, u + dx + wu + dx, v + dy + hu),
        "south": (u + 2 * dx + wu, v + dy, u + 2 * dx + 2 * wu, v + dy + hu),
    }


def recover_u_v(faces: dict) -> tuple[float, float] | None:
    if not all(f in faces and "uv" in faces[f] for f in FACES):
        return None
    u = min(faces[f]["uv"][0] for f in FACES)
    v = min(faces[f]["uv"][1] for f in FACES)
    return u, v


def box_of(element: dict) -> tuple[float, float, float, float, float] | None:
    """The (u, v, w, h, d) an element has to be judged on, or None if it cannot be.

    None means the element is not describing a Techne box at all: it omits faces, it
    is rotated (the rule is about an axis-aligned box), or a dimension is degenerate.
    """
    faces = element.get("faces") or {}
    u_v = recover_u_v(faces)
    if u_v is None or element.get("rotation"):
        return None
    u, v = u_v
    lo, hi = element["from"], element["to"]
    w = round(hi[0] - lo[0], 6)
    h = round(hi[1] - lo[1], 6)
    d = round(hi[2] - lo[2], 6)
    if w <= 0 or h <= 0 or d <= 0:
        return None
    return u, v, w, h, d


def follows_rule(element: dict, sizes: list[tuple[int, int]]) -> bool | None:
    """True when some sheet size explains every face, None when unjudgeable."""
    box = box_of(element)
    if box is None:
        return None
    for tex_w, tex_h in sizes:
        want = predict(*box, tex_w, tex_h)
        if all(rect_eq(element["faces"][name]["uv"], want[name]) for name in FACES):
            return True
    return False


class Verdict:
    """What is wrong with one element: the swaps we can repair, and anything else."""

    def __init__(self, swaps: list[tuple[str, str]], other: str | None):
        self.swaps = swaps
        self.other = other

    def describe(self) -> str:
        parts = [f"{a}/{b} swapped" for a, b in self.swaps]
        if self.other:
            parts.append(self.other)
        return "; ".join(parts)

    def repairable(self) -> bool:
        return bool(self.swaps) and not self.other


def analyse(element: dict, sizes: list[tuple[int, int]]) -> Verdict | None:
    """Returns a Verdict, or None when the element's unwrap is right or unjudgeable."""
    box = box_of(element)
    if box is None:
        return None
    u, v, w, h, d = box

    best: tuple[int, list[str], str] | None = None
    for tex_w, tex_h in sizes:
        want = predict(u, v, w, h, d, tex_w, tex_h)
        wrong = [name for name in FACES if not rect_eq(element["faces"][name]["uv"], want[name])]
        if not wrong:
            return None  # a clean unwrap on some sheet size
        if best is None or len(wrong) < best[0]:
            best = (len(wrong), wrong, f"{tex_w}x{tex_h}")

    assert best is not None
    _, wrong, size = best
    tex_w, tex_h = (int(x) for x in size.split("x"))
    want = predict(u, v, w, h, d, tex_w, tex_h)

    # Name the two swaps this project actually made, so the report is actionable.
    faces = element["faces"]
    swaps: list[tuple[str, str]] = []
    remaining = list(wrong)
    for a, b in (("up", "down"), ("east", "west")):
        if a in remaining and b in remaining \
                and rect_eq(faces[a]["uv"], want[b]) and rect_eq(faces[b]["uv"], want[a]):
            swaps.append((a, b))
            remaining = [f for f in remaining if f not in (a, b)]
    other = None
    if remaining:
        other = ("no consistent sheet size; closest " + size
                 + " still wrong on " + ", ".join(sorted(remaining)))
    return Verdict(swaps, other)


def repair(element: dict, swaps: list[tuple[str, str]]) -> None:
    """Swaps the two faces of each *detected* swap, in place.

    Only the pairs `analyse` actually named may be touched. Swapping both pairs
    unconditionally is wrong, and was wrong here: `coil.json`'s elements had only
    up/down transposed, so repairing both pairs fixed up/down and broke east/west,
    turning a two-face fault into a different two-face fault.
    """
    faces = element["faces"]
    for a, b in swaps:
        faces[a]["uv"], faces[b]["uv"] = faces[b]["uv"], faces[a]["uv"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--json", action="store_true", help="emit a JSON report")
    parser.add_argument("--fix", action="store_true",
                        help="repair elements whose only fault is the up/down or east/west swap")
    args = parser.parse_args()

    findings = []
    unjudged = []
    scanned = 0
    repaired_files = 0
    repaired_elements = 0
    for folder in MODEL_DIRS:
        for path in sorted(folder.glob("*.json")):
            model = json.loads(path.read_text(encoding="utf-8"))
            elements = model.get("elements") or []
            if not elements:
                continue
            sizes = referenced_sizes(model) + [s for s in CANDIDATE_SIZES if s not in referenced_sizes(model)]
            scanned += len(elements)

            # A file is only held to the Techne rule when it demonstrably follows it: if
            # half or more of the elements that *can* be judged already satisfy the rule,
            # the file came out of a Techne box and its stragglers are real faults. A file
            # where none do was authored face by face, and flagging it would be noise.
            verdicts = [follows_rule(element, sizes) for element in elements]
            judgeable = [v for v in verdicts if v is not None]
            clean = sum(1 for v in judgeable if v)
            if not judgeable or clean * 2 < len(judgeable):
                unjudged.append({
                    "file": str(path.relative_to(ROOT)).replace("\\", "/"),
                    "judgeable": len(judgeable),
                    "clean": clean,
                })
                continue

            touched = False
            for index, element in enumerate(elements):
                verdict = analyse(element, sizes)
                if verdict is None:
                    continue
                if args.fix and verdict.repairable():
                    repair(element, verdict.swaps)
                    touched = True
                    repaired_elements += 1
                    continue
                findings.append({
                    "file": str(path.relative_to(ROOT)).replace("\\", "/"),
                    "element": element.get("name", f"#{index}"),
                    "problem": verdict.describe(),
                })
            if touched:
                path.write_text(json.dumps(model, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
                repaired_files += 1

    if args.fix:
        print(f"repaired {repaired_elements} element(s) in {repaired_files} file(s)")

    if args.json:
        print(json.dumps({"scanned": scanned, "findings": findings, "not_judged": unjudged},
                         indent=2, ensure_ascii=False))
        return len(findings)

    print(f"scanned {scanned} element(s) across the block and item model folders")
    if findings:
        by_file: dict[str, list[dict]] = {}
        for finding in findings:
            by_file.setdefault(finding["file"], []).append(finding)
        print(f"\n{len(findings)} element(s) in {len(by_file)} file(s) still have a wrong unwrap:\n")
        for file, items in by_file.items():
            swaps = sorted({i["problem"] for i in items})
            names = ", ".join(i["element"] for i in items)
            print(f"  {file}")
            print(f"      {len(items)} element(s): {swaps[0] if len(swaps) == 1 else ' | '.join(swaps)}")
            print(f"      {names}")
    else:
        print("every Techne-derived model matches the vanilla rule")
    if unjudged:
        print(f"\n{len(unjudged)} file(s) were not judged - too few of their elements follow the"
              " Techne band layout, so they were authored face by face:")
        for entry in unjudged:
            print(f"  {entry['file']}  ({entry['clean']}/{entry['judgeable']} judgeable element(s) follow it)")
    return len(findings)


if __name__ == "__main__":
    sys.exit(main())
